### ISSUE TITLE
Unsupported device: iPad Mini 1 (P105AP) / iOS 9.0.2 (13A452)

### ISSUE THREAD

**Issue by Shrubbity** [Siguza/cl0ver#10]
I don't know if having no published firmware keys for this device prohibits success. I also used an old pre-compiled version (https://transipnemo.stackstorage.com/s/N5cYEXurrSoESym) so might be obsolete. 
No relevant panic log was produced on the device.

Anyway here goes:

```
Administrators-iPad:~ root# ./cl0ver panic
[*] Checking for config file... [src/lib/offsets.c:329 off_cfg]
[*] Nope, let's hope the registry has a compatible anchor & vtab... [src/lib/offsets.c:333 off_cfg]
[*] Using info leak to get kernel slide... [src/lib/slide.c:64 get_kernel_slide]
[*] Dict: [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[0]: 0x000000d3 [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[1]: 0x81000002 [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[2]: 0x08000004 [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[3]: 0x006c6f6c [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[4]: 0x84000400 [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[5]: 0x69696969 [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[6]: 0x69696969 [src/lib/slide.c:33 get_kernel_anchor]
[*] Spawning user client / Parsing dictionary... [src/lib/io.c:60 _io_spawn_client]
[*] Getting IO service handle... [src/lib/io.c:46 _io_get_service]
[*] Getting IO master port... [src/lib/io.c:31 get_io_master_port]
[*] Creating dict iterator... [src/lib/io.c:73 _io_iterator]
[*] Getting next element from iterator... [src/lib/io.c:85 _io_next]
[*] Releasing user client... [src/lib/io.c:132 _io_release_client]
[*] Kernel stack: [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 0]: 0x69696969 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 1]: 0x00000000 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 2]: 0x9d259598 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 3]: 0x00000004 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 4]: 0xb408aab8 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 5]: 0x80d40d7c [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 6]: 0xb8f7ac00 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 7]: 0x80d40da0 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 8]: 0x893d3ea0 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 9]: 0x9cea78b3 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[10]: 0x00001068 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[11]: 0x00001068 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[12]: 0xb408aa00 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[13]: 0x00000000 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[14]: 0x80d40800 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[15]: 0x9d218988 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[16]: 0x00001068 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[17]: 0x00000000 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[18]: 0x893d3f38 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[19]: 0x9ce106bf [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[20]: 0xb9f44230 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[21]: 0x00000000 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[22]: 0x00000000 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[23]: 0x893d3f70 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[24]: 0x00000015 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[25]: 0x00000f03 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[26]: 0x00000000 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[27]: 0xdd31e7b0 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[28]: 0xb408aa00 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[29]: 0x00000012 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[30]: 0xbc4f0624 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[31]: 0x9d259598 [src/lib/slide.c:44 get_kernel_anchor]
[*] Getting anchor address from registry... [src/lib/offsets.c:227 reg_anchor]
[*] Model: P105AP [src/lib/offsets.c:128 get_model]
[*] OS build: 13A452 [src/lib/offsets.c:196 get_os_version]
[!] Unhandled error: Unsupported device [src/lib/offsets.c:256 reg_anchor]
```

**Comment by Siguza** [comment]
Judging by line numbers, I think your version of cl0ver is out of date. Please try again with the current revision. :)

**Comment by Shrubbity** [comment]
Is there a pre-compiled binary you could link/upload?

I tried compiling with make (on my VM w/ xcode + cmd tools installed) but alas was met with many compile errors :/ no doubt due to my ineptitude

**Comment by Siguza** [comment]
Sure: [cl0ver.zip](https://github.com/Siguza/cl0ver/files/695077/cl0ver.zip)

But would you mind giving me a dump of these compile errors? Because it's supposed to compile with just the iOS SDK...

**Comment by Shrubbity** [comment]
Here's are the compile errors:

http://pastebin.com/ShJiBSUG


Running your binary certainly caused my device to panic, though it hangs on 'releasing user client' until 5 minutes later I pressed enter.

I've got two panic logs, not sure if they contain anything useful:

Panic 1: http://pastebin.com/zXqSmxrD

Panic 2: http://pastebin.com/kcGtX9yV

**Comment by Siguza** [comment]
Tells me that `__DATA.__const` starts at `0x803e8000`. If we're lucky, this will put the OSString vtable at `0x803ede48`.  
But we still need an anchor, for which I need both a panic log and the corresponding output from cl0ver.

As for the compiler errors... XCode without the iOS SDK? Never seen that before... could you try running `xcodebuild -showsdks`?

**Comment by Shrubbity** [comment]
As to the compiler errors, it seems my xcode path was messed up somehow. Resetting it with 'xcode-select --r' fixed the issues!

oops, my apologies for missing the corresponding cl0ver log out.

There it is:
http://pastebin.com/5PcbHFk1

It hangs on Releasing User Client.


This one got further but didn't produce a panic log: http://pastebin.com/UQDyLWRk.

**Comment by Shrubbity** [comment]
Would appreciate update

**Comment by Siguza** [comment]
Okay, this is all based on guesswork, since there is virtually no info available on the iPad Mini's kernel, but try this:  
Create a file at `/etc/cl0ver/config.txt` with the following contents:

    0x800a78b3
    0x803ede48

Then try running `./cl0ver dump`.

**Comment by Shrubbity** [comment]
Oops, completely forgot, will do so soon!

**Comment by Shrubbity** [comment]
Here's the terminal output:
http://pastebin.com/SZbywtKG

Here's the panic log:
http://pastebin.com/LCQUANd5


If you want me to run it again can do!

**Comment by Siguza** [comment]
If you try multiple times - does it ever reach a point where it lists segments like `__TEXT`, `__DATA`, etc.?

**Comment by Shrubbity** [comment]
Alas no, it's very hit or miss, sometimes I'll get no panic logs, sometimes only panic logs with CRC error, or sometimes advancing only as far as the last log I linked.

I've tried when the device is idle, stressed and in no substrate mode.

I'm happy to keep trying if you have any other ideas though.

**Comment by Siguza** [comment]
In that case, the config values are almost certainly wrong, so there's no point in trying any further.

I don't know what else to try.  
The iPad Mini is the only 32-bit device of its line, doesn't share a kernel with anything, has never had any keys released, is not vulnerable to my vtab leak, is not supported by iOS 10 with its decrypted kernels... this is the saddest device in the world! D:

**Comment by Shrubbity** [comment]
:(

I knew it, unfortunately those people that have the capabilities won't release the keys, so indeed, it is the saddest of the saddest devices.

Is there no script you could write which could automate something?

My laptop and iPad Mini are at your disposal indefinitely!!

**Comment by Siguza** [comment]
Hold on, I might have been an idiot... what happens if you use these?:

    0x800a78b3
    0x803ede50

**Comment by Shrubbity** [comment]
Ey, something seems to be happening now! _TEXT indeed! Though my panic logs are giving me CRC errors.

pastebin.com/yKcUViKr


Woo!

**Comment by Siguza** [comment]
Alright, I've been an idiot. ^^  
The values were in front of me all the time, I just forgot to add the 8 byte offset from the symbol table's entry.
Also, looked around for some more info on shared kernels, and from the offsets of [Home Depot](http://wall.supplies/offsets.html), it seems that the iPad Mini and the iPad 3 have identical offsets. And for the iPad 3, keys _are_ available en masse!  
Now, cl0ver never supported 32-bit devices beyond kernel dumping, but I'm gonna take the time to add iPad 3/9.0.2 offsets to my fork of Trident, and then we can see if that works for you.

**Comment by Shrubbity** [comment]
Wonderful! Thanks a lot.

**Comment by Siguza** [comment]
Just a quick update: it'll be a while longer before I can get to this. I'm buried under uni stuff and a server to migrate. But I haven't forgotten about you.

**Comment by Shrubbity** [comment]
Cheers, whenever you got the time is great :)!

**Comment by Shrubbity** [comment]
Hey, not to nag as you've already said you're busy, I'm just wondering if you've looked at it thus far?

tfp0 appears to have even more use with tihmstar's recent 32-bit update!

**Comment by Siguza** [comment]
You're right, I've been putting it off for quite a while. [It's done now](https://github.com/Siguza/Trident).  
I did add the offsets as `iPad3,3` though, so as a quick 'n dirty way to test them on your iPad mini, change this line in offsetfinder.c:

    determineTarget("iPad3,3", "9.0.2", iPad33_iOS902);

to this:

    determineTarget("iPad2,5", "9.0.2", iPad33_iOS902);

**Comment by Shrubbity** [comment]
Thanks a lot! I appreciate your efforts.

I couldn't work out where to change offsetfinder.c as it seemed to belong to your fork of 'Trident'. I git cloned it into the cl0ver folder and altered it anyway but I'm not sure if it was used when I compiled. Any help here would be appreciated.

Here's the result of a few dumps just for the sake of it: https://pastebin.com/dsYuPfR4
The kernel slide value seems to change a bit time to time.

**Comment by Siguza** [comment]
Huh? I think you got it wrong.

You can do away with cl0ver entirely, it doesn't support 32-bit to a useful level, and it never will. You're supposed to use just my Trident fork, without cl0ver.

**Comment by Shrubbity** [comment]
Ah indeed, my bad! Well, I compiled and signed trident via xcode and changed the deployment version so that it would sign.

Initially when app opening it said it - iOS 9.0.2 (not supported) and YOLO was grayed out. I went through and manually copied the values for iPad 3,3 for 2,5 and that appeared to do the trick.

I compiled and installed your ios-kern-utils and ran kmap, that gave me a long spiel of addresses. Does that mean it was successful?

**Comment by Siguza** [comment]
Yes, that means success! Woo! \o/ :D

**Comment by Shrubbity** [comment]
Wooo that's great news! Thanks a lot!

**Comment by Siguza** [comment]
You're welcome. In light of that, I'm closing this issue then. :)
