### ISSUE TITLE
iPhone 6s on iOS 9.0.1 (13A405)

### ISSUE THREAD

**Issue by W00dL3cs** [Siguza/cl0ver#13]
Preparing for iOS 10.2 jailbreak, but it seems that currently Cl0ver does not support my device (iPhone 6s on iOS 9.0.1)... so, I'd appreciate if you could give these logs a look:

./cl0ver log: http://pastebin.com/5eRG3zRp
./cl0ver panic log: http://pastebin.com/uU4j4ntW

Thank you in advance, man! :)

**Comment by Siguza** [comment]
I'll need the actual *kernel* panic log to go with that, otherwise the output you provided is pretty meaningless I'm afraid.

**Comment by W00dL3cs** [comment]
Yeah, I thought the same... but that's everything I've got: I mean, I don't have any trace of any kernel panic log in my diagnostics.

Tried 3 times so far, am I supposed to keep trying?

**Comment by W00dL3cs** [comment]
Nevermind, got one:

http://pastebin.com/h1J4xhgD

**Comment by Siguza** [comment]
Aight, I'll have a look at it tomorrow. :)

**Comment by Siguza** [comment]
So... I'll still look into this if you want me to, but in light of the 10.2 jailbreak having been dropped and the 10.2 signing window still being open, it might be wiser to just update right now.

**Comment by W00dL3cs** [comment]
Yeah, it seems that I called it... I'm going to update to iOS 10.2 in the next hours (hopefully), but I don't know if anyone else will ever need these offsets in future, so it's really up to you if giving a look at the logs or not.
Thanks anyway for your support, really appreciated it :)

**Comment by Siguza** [comment]
Okay, I finally got round to taking a look. The value in the panic log is too far out to possibly be the vtable... guess my heap feng shui wasn't enough.

Since both of us can't do anything about it now, I'm closing this ticket.
