### ISSUE TITLE
iPhone 6s+ iOS 9.0.2 Unsupported device/OS combination

### ISSUE THREAD

**Issue by Meijerbink** [Siguza/cl0ver#14]
Model: N66AP
OS build: 13A452

Where can i find the kernel panic log on my iPhone, or what is the terminal command?

**Comment by Siguza** [comment]
I'm not sure where they're stored, actually... could be `/var/logs/CrashReporter/panics`.  
But they should show up under Settings > Privacy > Diagnostics & Usage > Diagnostics & Usage Data, or when connected to a computer, they can be retrieved with either XCode (Window > Devices > (select your device) > View Device Logs) or libimobiledevice (`idevicecrashreport`).

**Comment by Meijerbink** [comment]
http://pastebin.com/SR0LaH6t

This is the panic file

**Comment by Meijerbink** [comment]
And the cl0ver log:

http://pastebin.com/5EKn9ufE

**Comment by Meijerbink** [comment]
And another panic log:

http://pastebin.com/3EbzaJt9

**Comment by mequm** [comment]
Try these settings in your /etc/cl0ver/config.txt
0xffffff800453e000
0xffffff80044f7168

**Comment by Meijerbink** [comment]
I have updated to 10.2. We can close this.
