### ISSUE TITLE
Unsupported device: iPad Air 2 (J82AP) / iOS 9.0.2 (13A452)

### ISSUE THREAD

**Issue by HaikuZen** [Siguza/cl0ver#17]
[panic.log.txt](https://github.com/Siguza/cl0ver/files/748243/panic.log.txt)

**Comment by Siguza** [comment]
The line numbers from the log suggest you're using quite an old build of cl0ver. Please try again with the [latest version](https://github.com/Siguza/cl0ver/releases).

**Comment by NeoMan-Hx** [comment]
Can you upload a precompiled file?
I tried to compile but there were a lot of errors.

**Comment by brymonster** [comment]
Same issue here 
iPad4,1 J71AP

**Comment by HaikuZen** [comment]
Just tried with the 1.0.2 version
[tmp_15925-panic_new.log-1813411859.txt](https://github.com/Siguza/cl0ver/files/751243/tmp_15925-panic_new.log-1813411859.txt)

ps 
When issued the command
./cl0ver panic log=panic.log
Ipad rebooted

**Comment by Siguza** [comment]
I'll have time to look at this tomorrow - why did you close it?

**Comment by brymonster** [comment]
My issue persists. 
Kernel slide not a multiple of 0x100000.

Thanks

**Comment by HaikuZen** [comment]
Sorry, my fault :(
wrong button

**Comment by Siguza** [comment]
@brymonster You're using config values that weren't meant to be used with your device.

Both of you: I need the output of running `./cl0ver panic` **as well as** the device's panic log. Please see the [readme](https://github.com/Siguza/cl0ver#usage) and follow the "Usage" part closely.

**Comment by brymonster** [comment]
i was using incorrect offsets and config file. i wrongly assumed something was better than nada.
im getting results now! thanks for all your help.  
[panic log.txt](https://github.com/Siguza/cl0ver/files/752739/panic.log.txt)
[panic output.txt](https://github.com/Siguza/cl0ver/files/752740/panic.output.txt)

**Comment by Siguza** [comment]
Okay, anchor seems to be `0xffffff800453e000`, but it doesn't tell me the vtable, unfortunately.

This is a complete longshot, but could you try running `./cl0ver` with the [iPhone 6s offsets](https://raw.githubusercontent.com/Siguza/cl0ver/master/offsets/N71AP_13A452/offsets.dat) and these values in `config.txt`:

    0xffffff800453e000
    0xffffff80044f7168

If that crashes your device, you'll have to do another round of `./cl0ver panic`, and hopefully that'll produce a log that tells me more.

**Comment by brymonster** [comment]
`[*] Checking for config file... [src/lib/offsets.c:106 off_cfg]
[*] Yes, attempting to read anchor and vtab from config file... [src/lib/offsets.c:116 off_cfg]
[!] Unhandled error: Failed to parse config file. Please either repair or remove it. [src/lib/offsets.c:126 off_cfg]
`

**Comment by Siguza** [comment]
Are you on Windows? If so, make sure to use `\n` line endings, and not `\r\n`. If not... what are the raw contents of you config.txt?

**Comment by brymonster** [comment]
Mac. 
i have in my config only what you told me:
0xffffff800453e000
0xffffff80044f7168
`./clover slide` gives me: "Unhandled error: Unsupported device"

**Comment by Siguza** [comment]
Something must be wrong with that config... did you check for whitespace? Or could you delete it and use something like `nano` to recreate it and make sure it contains no control characters, or BOM, or something like that?

**Comment by brymonster** [comment]
english please? lol sorry im not a dev/researcher. just found your patch and tried the best i could.

**Comment by Siguza** [comment]
Well okay, try this: As root on your iPad, run this:

    echo -e '0xffffff800453e000\n0xffffff80044f7168' >/etc/cl0ver/config.txt;

Then try running cl0ver again, and see whether it still complains about a broken config.

**Comment by HaikuZen** [comment]
Here it is 
[tmp_16508-slide.log-680476411.txt](https://github.com/Siguza/cl0ver/files/769349/tmp_16508-slide.log-680476411.txt)
[tmp_16508-panic.log456005437.txt](https://github.com/Siguza/cl0ver/files/769350/tmp_16508-panic.log456005437.txt)

**Comment by Siguza** [comment]
Okay, let's get this sorted out:

@brymonster: You've been using the wrong thread. This is about the iPad Air 2, you have an iPad Air 2. I'm referring you to issue #34.

@HaikuZen I'm sorry for not sooner detecting this - everything I've told brymonster is very unlikely to work for you. Try with these values in your config:

    0xffffff800454a000
    0xffffff8004503168

**Comment by NeoMan-Hx** [comment]
This is available, thanks!

**Comment by ABABREPO** [comment]
Hallo i have Unsupported device: iPad Air 2 (J82AP) / iOS 9.0.2 (13A452) I have Jailbreak, I want to use Prometheus And upgrade to ios 10 or 11, I have a problem with no danger Enable tfp0 on iOS 9 Jailbreak. Where to profit offset for the Ipad Air 2 cellular. iPad Air 2 (J82AP)
thank you veru much for help me. sotry ma english

**Comment by gummykage** [comment]
Siguza, I have an iPad Air 2 Cellular model from USA that's also on 9.0.2. Are there any known offsets for this already?

**Comment by gummykage** [comment]
My apologies I'm learning github for the first time, and just realized there is possibly a solution for ipad Air 2 already working from the config / kernel post you made in the "closed" tickets area. I will try that first and report back. Thank you Siguza. Could you take a look at the ipad mini 4 panic logs in the other ticket instead =D

**Comment by gummykage** [comment]
Siguza, this worked perfectly. Thank you so much!!! (ipad 2 cellular on 9.0.2 successful)

It's on 11.3.1 now.
