### ISSUE TITLE
“Bad CPU type in executable“

### ISSUE THREAD

**Issue by leandroprz** [Siguza/cl0ver#18]
I tried running the v1.0.2 binary and I got this error: “Bad CPU type in executable“. Then I downloaded the source code and compiled it but I'm still getting the same error.

I'm using Sierra v10.12.2

Any idea what could be causing this?

**Comment by Siguza** [comment]
You're supposed to run it on iOS, not OS X.

**Comment by leandroprz** [comment]
Oh, I feel such an idiot. Okay, I'll give it a try directly from my 6S.

Where should I put the binary?

**Comment by Siguza** [comment]
> Where should I put the binary?

Doesn't matter. But if you happen to be on 9.0.2, you might wanna grab [an offsets file](https://github.com/Siguza/cl0ver/tree/master/offsets).

**Comment by leandroprz** [comment]
I'm on 9.0.2 but I have the TSMC chip on my 6S (N71mAP), that offset isn't listed there. How can I find the correct offset for my device?

**Comment by ryu16** [comment]
@leandroprz I think you can try N71AP's offsets file.

**Comment by leandroprz** [comment]
@ryu16 That didn't work. It crashed my device.

`./cl0ver slide` works, but I can't pass from that one. `./cl0ver dump` also crashes my device and the  decryption keys for my firmware are not available.

**Comment by ryu16** [comment]
@leandroprz I've experienced crash when using ssh terminal, so I used MTerminal or WhiteTerminal without network connection to run cl0ver. How is it?

**Comment by leandroprz** [comment]
@ryu16 I was using PuTTY on Windows. Tried with MTerminal and it crashed. I was able to make it work with WhiteTerminal and airplane mode On, then patched the device just fine. Thank you!

@Siguza I'm not sure if my kernel.bin file would be useful for somebody else, but I made a copy just in case. Ley me know if you need it.
