### ISSUE TITLE
N66mAP, 13A452 (iPhone 6s+, iOS 9.0.2) Unsupported device/OS combination

### ISSUE THREAD

**Issue by colereynolds** [Siguza/cl0ver#20]
I followed your instructions and below is the panic log with 0xffffff80... and the output from the "./cl0ver panic log=panic.log". Do you need anything else to add support for my device?

I just compiled this myself a day or so ago. If I need to build and run the latest version, let me know!

Thank you in advance!

These files are from the latest successful panic attempt:
[panic-2017-02-03-093756.ips.txt](https://github.com/Siguza/cl0ver/files/750905/panic-2017-02-03-093756.ips.txt)
[panic.log.txt](https://github.com/Siguza/cl0ver/files/750906/panic.log.txt)

These files are the output from running the other cl0ver parameters, just in case you need it:
[slide.txt](https://github.com/Siguza/cl0ver/files/750921/slide.txt)
[patch.txt](https://github.com/Siguza/cl0ver/files/750922/patch.txt)
[dump.txt](https://github.com/Siguza/cl0ver/files/750923/dump.txt)

**Comment by ryu16** [comment]
Since 6s+ would be same as 6s, you can try again after making `/etc/cl0ver/config.txt` with these 6s values:
`0xffffff800453e000`
`0xffffff80044f7168`

If you run `cl0ver panic` many times, you'll see two kind of panic logs which  one is good and other is bad. If you have good panic logs, it will help finding  new values to support new kernel. :)

- Bad panic logs are like:
`"panicString" : "panic(cpu 0 caller 0xffffff80180fc954): `**PC alignment exception**` from kernel.`

- Good panic logs are like:
`"panicString" : "panic(cpu 1 caller 0xffffff800e8fd510): \"`**Kernel instruction fetch abort**`: pc=`**0xffffff800ecf7168**

**Comment by colereynolds** [comment]
Is it safe to use those 6s values, or would it be risky? 

Do I need to keep running "./cl0ver panic" until I get a "good" panic log to verify?

**Comment by colereynolds** [comment]
I attempted to use the 6s TSMC values (see link below) from the offsets folder, but I still got the same error in the log and kmap didn't work after either. 

https://raw.githubusercontent.com/Siguza/cl0ver/master/offsets/N71mAP_13A452/offsets.dat

Attached is the log from my patch attempt:

[patch.log.txt](https://github.com/Siguza/cl0ver/files/752425/patch.log.txt)

**Comment by Siguza** [comment]
In your case, you'd need both `config.txt` and `offsets.dat`. Try doing what ryu16 suggested, i.e. create a file at `/etc/cl0ver/config.txt` with these contents:

    0xffffff800453e000
    0xffffff80044f7168

Using values from a different device just has the chance of crashing your device, nothing more.  
And if you installed both files, try running just `./cl0ver` - if it works, you're done and the values work. If it crashes, then the values don't work and you'll have to go back to `./cl0ver panic`.

**Comment by colereynolds** [comment]
Ah, that's what I was missing! I used both files and it patched successfully. I even tried kmap after and it worked!

Thank you guys so much for your help! You can now add my device and build to the list of supported devices! 😃

**Comment by Siguza** [comment]
Added as of cc460b0cfb21a4c9c328164cb3021650942fa47f. :)
