### ISSUE TITLE
Iphone 6s(iPhone8,1) Model: N71mAP  IOS:9.0.1 build: 13A405 Unsupported

### ISSUE THREAD

**Issue by Sultan4tech** [Siguza/cl0ver#22]
i have tried the commands ./cl0ver slide, ./cl0ver and ./cl0ver dump but they don't work and there was no crash either so no panic log.

thank you and i hope this help to support 9.0.1

[saved output.txt](https://github.com/Siguza/cl0ver/files/752868/saved.output.txt)

**Comment by Sultan4tech** [comment]
after running ./cl0ver panic i got panic log after the crash

the output and the log attached
[output.txt](https://github.com/Siguza/cl0ver/files/754312/output.txt)
[panic-2017-02-06-133024.txt](https://github.com/Siguza/cl0ver/files/754316/panic-2017-02-06-133024.txt)

**Comment by Sultan4tech** [comment]
yes, successfully installed patch :)

i have used the following values in the config file, after reviewing some closed issues from devices with the same kernel version 
`0xffffff800453e000
0xffffff80044f7168`

i was able to dump the kernel.bin and run ./cl0ver, the patch installed successfully, also i enabled nonce without any problems.

here is the offsets file for N71mAP_13A405, I'm not able to upload zip file here in github. says "We don’t support that file type. " :s
https://ufile.io/9a0a81
THANK YOU SO MUCH, GREAT WORD YOU DID.

**Comment by Siguza** [comment]
You're welcome, thanks for the offsets file. :)
Merged: c67231d82636bee5855aaaba0ed8f3d423aba101
