### ISSUE TITLE
Iphone 5s (6,2) 9.0.2 Pangu 

### ISSUE THREAD

**Issue by noworrries** [Siguza/cl0ver#24]
Hello, pretty much the same as the person before, though I got a iphone 5s iphone6,2

[https://gist.github.com/noworrries/4d4824abc59b1efbe7cdc342806cc558](https://gist.github.com/noworrries/4d4824abc59b1efbe7cdc342806cc558 )

Seems to offsets of the previous poster work and am trying to get kernel.bin now.

If I am mistaken, pls correct me.

Thanks for the tool and the offer for help.

**Comment by goodbest** [comment]
Maybe you can try my values and offsets first, maybe it will work fine on both iPhone6,1 and 6,2.
https://github.com/Siguza/cl0ver/issues/23

Dumping kernel is really painful.

**Comment by noworrries** [comment]
Thanks a lot goodbest for getting the kernel, was already at 30plus reboots...
Thanks Siguza for your terrific work. 

Your offset.dat works for 6,2 fine.

**Comment by goodbest** [comment]
So does that mean iPhone6,1(N51AP) and iPhone6,2(N53AP) share the same `config.txt` and `offsets.dat` on 9.0.2?
If it is true, we can also add support for N53AP in the src.

**Comment by Siguza** [comment]
> So does that mean iPhone6,1(N51AP) and iPhone6,2(N53AP) share the same `config.txt` and `offsets.dat` on 9.0.2?

That seems to be what they said.
Merged: 3253e25525ffa65bfe712f411565fc344a016645 :)
