### ISSUE TITLE
Unsupported device/OS combination iPhone 5s (6,2) ios 9.0.2

### ISSUE THREAD

**Issue by binhtien06** [Siguza/cl0ver#27]
please help me run this file. I copied the pre-compiled cl0ver (1.0.3) into directory / of my device and run it as your instruction but the result is as follows:

[] Checking for config file... [src/lib/offsets.c:124 off_cfg]
[] Nope, let's hope the registry has a compatible anchor & vtab... [src/lib/offsets.c:128 off_cfg]
[] Page size: 0x0000000000001000 [src/lib/uaf_rop.c:113 uaf_rop_stack]
[] Allocating ROP stack page at 0x000000000c000000 [src/lib/uaf_rop.c:117 uaf_rop_stack]
[] Allocated ROP page at 0x000000000c000000 [src/lib/uaf_rop.c:123 uaf_rop_stack]
[] Initializing offsets... [src/lib/offsets.c:164 off_init]
[] Checking for offsets cache file... [src/lib/offsets.c:177 off_init]
[] Using info leak to get kernel slide... [src/lib/slide.c:64 get_kernel_slide]
[] Dict: [src/lib/slide.c:33 get_kernel_anchor]
[] dict[0]: 0x000000d3 [src/lib/slide.c:33 get_kernel_anchor]
[] dict[1]: 0x81000002 [src/lib/slide.c:33 get_kernel_anchor]
[] dict[2]: 0x08000004 [src/lib/slide.c:33 get_kernel_anchor]
[] dict[3]: 0x006c6f6c [src/lib/slide.c:33 get_kernel_anchor]
[] dict[4]: 0x84000400 [src/lib/slide.c:33 get_kernel_anchor]
[] dict[5]: 0x69696969 [src/lib/slide.c:33 get_kernel_anchor]
[] dict[6]: 0x69696969 [src/lib/slide.c:33 get_kernel_anchor]
[] Spawning user client / Parsing dictionary... [src/lib/io.c:59 _io_spawn_client]
[] Getting IO service handle... [src/lib/io.c:45 _io_get_service]
[] Getting IO master port... [src/lib/io.c:30 get_io_master_port]
[] Creating dict iterator... [src/lib/io.c:72 _io_iterator]
[] Getting next element from iterator... [src/lib/io.c:84 _io_next]
[] Releasing user client... [src/lib/io.c:131 _io_release_client]
[] Kernel stack: [src/lib/slide.c:44 get_kernel_anchor]
[] buf[ 0]: 0x6969696969696969 [src/lib/slide.c:44 get_kernel_anchor]
[] buf[ 1]: 0xffffff801133e000 [src/lib/slide.c:44 get_kernel_anchor]
[] buf[ 2]: 0x00000000ff002bf1 [src/lib/slide.c:44 get_kernel_anchor]
[] buf[ 3]: 0xffffff8115b305cc [src/lib/slide.c:44 get_kernel_anchor]
[] buf[ 4]: 0xffffff81130fd6b4 [src/lib/slide.c:44 get_kernel_anchor]
[] buf[ 5]: 0xffffff811697e700 [src/lib/slide.c:44 get_kernel_anchor]
[] buf[ 6]: 0xffffff8115b305a0 [src/lib/slide.c:44 get_kernel_anchor]
[] buf[ 7]: 0xffffff8010243950 [src/lib/slide.c:44 get_kernel_anchor]
[] buf[ 8]: 0xffffff8010ed5f40 [src/lib/slide.c:44 get_kernel_anchor]
[] buf[ 9]: 0x0000000000000000 [src/lib/slide.c:44 get_kernel_anchor]
[] buf[10]: 0xffffff8011344a50 [src/lib/slide.c:44 get_kernel_anchor]
[] buf[11]: 0xffffff8115b30000 [src/lib/slide.c:44 get_kernel_anchor]
[] buf[12]: 0xffffff8011392cc0 [src/lib/slide.c:44 get_kernel_anchor]
[] buf[13]: 0x0000000000001074 [src/lib/slide.c:44 get_kernel_anchor]
[] buf[14]: 0x0000000000000000 [src/lib/slide.c:44 get_kernel_anchor]
[] buf[15]: 0xffffff8011392050 [src/lib/slide.c:44 get_kernel_anchor]
[] Getting anchor address from registry... [src/lib/offsets.c:25 reg_anchor]
[] Model: N53AP [src/lib/device.c:34 get_model_internal]
[] OS build: 13A452 [src/lib/device.c:102 get_os_version_internal]
[!] Unhandled error: Unsupported device/OS combination [src/lib/offsets.c:53 reg_anchor]

I'm noob at programming, please help. Thank you

**Comment by Siguza** [comment]
1. Download [1.0.4](https://github.com/Siguza/cl0ver/releases/tag/1.0.4)
2. Put [this file](https://raw.githubusercontent.com/Siguza/cl0ver/master/offsets/N51AP_13A452/offsets.dat) at `/etc/cl0ver/offsets.dat`
3. Run `./cl0ver` without any arguments

**Comment by binhtien06** [comment]
Thank you so much. I've done tfp0 patch successfully with cl0ver 1.0.4, so happy
