### ISSUE TITLE
iPhone 6 N61AP iOS 9.0.2 cl0ver dump crash

### ISSUE THREAD

**Issue by helomen** [Siguza/cl0ver#28]
Here the [Panic Log](http://pastebin.com/95bxKpnE)
and the [cl0ver slide](http://pastebin.com/DZvQTi1Q) file
Unfortunately the cl0ver dump command always crashes and the iPhone resets without any result.
How shall I continue?

**Comment by helomen** [comment]
It finally worked... I copied the right offsets.dat into the correct directory. Thx for this nice tool.

**Comment by Siguza** [comment]
You're welcome. :)
