### ISSUE TITLE
Unsupported device/OS combination iPhone 6S (N71mAP) ios 9.0 (13A342)

### ISSUE THREAD

**Issue by hey101** [Siguza/cl0ver#29]
I didn't see an offset file for ios 9.0 for my iPhone 6S. I ran cl0ver panic but after 100 attempts so far it still has not generated a panic ips file. Any ideas or suggestions? I have disabled find my iphone and tried it with airplane mode on. 

I am using pangus jailbreak for iOS 9.0.

Output from panic so far: [Pastebin](http://pastebin.com/GZjCASt8)

Update:
I have continuously tried crashing my phone for a couple hours. I have tried everything from opening various apps, tweaking settings, trying safe mode and others. I have yet to get a single panic log. If you have any suggestions then I am open to them. The only thing I haven't tried is building cl0ver myself or using an older version. I do have a ton of JetsamEvent logs but I do not think they are of any use. 

Update #2 
I have done close to 1000 panics and still not a single panic log :/. I have probably spent about 6+ hours trying during my spare time using ssh to panic the device. Any suggestions? I feel like I am completely missing something....

Update #3 
I have tried every version of the pre compiled version of cl0ver but still no success :/. It's actually becoming quite frustrating, so I think I will just wait till someone replies here for suggestions and hope that I can get something working,

**Comment by Siguza** [comment]
Sorry for taking so long, I'm currently on vacation.

But... I'm not sure I can help on this. My devices all generate panic logs pretty much all the time, except for my iPhone SE, which only does so every 20th time or so, and I have no idea what's causing it.  
I can only suggest waiting half a minute after unlocking the device, as it takes some time to dump the data from NVRAM to disk... but other than that I'm clueless I'm afraid.

However, you could just try and use the anchor and offset of 9.0.1, i.e.:

    0xffffff800453e000
    0xffffff80044f7168

It's a stab in the dark, but almost all offsets stayed the same from 9.0.1 to 9.0.2, so... it might work.

**Comment by hey101** [comment]
Well you are on vacation, so go enjoy it instead of posting here lol.

But thank you! Your stab in the dark worked and those offsets worked perfectly. I now have the patch done successfully!

Here is my offset file in case it helps others.
[offsets.zip](https://github.com/Siguza/cl0ver/files/769055/offsets.zip)

**Comment by Siguza** [comment]
Aaand they're exactly the same as for N71mAP/9.0.1. ^^  
But thanks, that's useful information. :)

And don't worry, I'm getting my fair share of skiing up here. ;)
