### ISSUE TITLE
Cl0ver panic

### ISSUE THREAD

**Issue by HiddenUnkn0wn** [Siguza/cl0ver#33]
http://pastebin.com/dvcEWrMf

**Comment by Siguza** [comment]
Okay, there's something I've never seen before: a value *lower* than the kernel base.  
I'm afraid that can't be the value we're looking for. :/

**Comment by HiddenUnkn0wn** [comment]
I'm sorry I posted a new one that I believe meets the criteria. Took me 6 -7 tries.

**Comment by Siguza** [comment]
Alright, I'm closing this then in favour of #34.
