### ISSUE TITLE
Unsupported device: iPad Air 2 (J81AP) / iOS 9.0.2 (13A452)

### ISSUE THREAD

**Issue by guitahero** [Siguza/cl0ver#37]
Hi, here's what I think is a useful log for the ipad air 2 (first revision J81AP model)

[SLIDE_panic-2017-02-14-100819.txt.txt](https://github.com/Siguza/cl0ver/files/774054/SLIDE_panic-2017-02-14-100819.txt.txt)
[panic-2017-02-14-100819.txt](https://github.com/Siguza/cl0ver/files/774011/panic-2017-02-14-100819.txt)
[Output_panic-2017-02-14-100819.txt](https://github.com/Siguza/cl0ver/files/774012/Output_panic-2017-02-14-100819.txt)

**Comment by Siguza** [comment]
Alright, please try with these values in your config:

    0xffffff800454a000
    0xffffff8004503168

**Comment by guitahero** [comment]
Apparently it worked. After running kmap command a bunch of stuff appear.


[j81ap_offsets.dat.txt](https://github.com/Siguza/cl0ver/files/776532/j81ap_offsets.dat.txt)

**Comment by guitahero** [comment]
I am restoring! Uhuu. My purpouse was to restore to 10.2 from 9.0.2. Thank you, your help was invaluable to me.

**Comment by Siguza** [comment]
Glad to be of help, thanks for the offsets file. :)
