### ISSUE TITLE
Unsupported device: iPhone 6s (N71AP) / iOS 9.0.1 (13A405)

### ISSUE THREAD

**Issue by eramirez3** [Siguza/cl0ver#41]
[panic-2017-02-22-101031.txt](https://github.com/Siguza/cl0ver/files/793955/panic-2017-02-22-101031.txt)
[panic6log.txt](https://github.com/Siguza/cl0ver/files/793956/panic6log.txt)

Please could you help me to add support to an iPhone 6S N71AP with iOS 9.0.1, here y attach the log and crash report

Thank you on advance

David

**Comment by Siguza** [comment]
Your log didn't include all the necessary information, but given the amounts of pre-existing data on similar models and iOS versions, I hacked up a config...

    0xffffff800453e000
    0xffffff80044f7168

...as well as an [offsets file](https://github.com/Siguza/cl0ver/files/794114/offsets.dat.zip) that I think should work.  
Try installing both, and running `./cl0ver` with no arguments.

If that crashes your device, remove the offsets file but keep the config, and try running `./cl0ver dump`.

**Comment by eramirez3** [comment]
It worked

Thank you

**Comment by Siguza** [comment]
Cool, merged: 6387cacaa62241d31e403afd0116b58089527587 :)
