### ISSUE TITLE
Unsupported device: iPad Mini 4 (J96AP) / iOS 9.3.3 (13G34)

### ISSUE THREAD

**Issue by BasMulders** [Siguza/cl0ver#42]
Hopefully this log contains enough information: http://pastebin.com/LqAfuKRa

Thanks!

**Comment by Siguza** [comment]
Nope, can't tell anything from that log unfortunately. It'd have to be a "Kernel instruction fetch abort", and I'd need the actual output of cl0ver in addition to the panic log.

But since you're on 9.3.3, doesn't [jbme.qwertyoruiop.com](https://jbme.qwertyoruiop.com) work for you?

**Comment by BasMulders** [comment]
You're right! I tried that for a couple of hours but gave up since nonceEnabler kept crashing. Tried to do it via cl0ver but that clearly did not work out yet either. Seems like I got it working now though, via the 9.3.3. jbme!
