### ISSUE TITLE
Unsupported device: iPhone 5S (N51AP) / iOS 9.3.3 (13G34)

### ISSUE THREAD

**Issue by timonline** [Siguza/cl0ver#43]
cl0ver panic output: http://pastebin.com/UJbFu11U
cl0ver panic log: http://pastebin.com/Uj5aqGvN

cl0ver slide output: http://pastebin.com/hJDaYvFQ

Let me know if you need anything else

*Update* I was hoping to get the cl0ver working because the https://jbme.qwertyoruiop.com/ keeps crashing and never succeeds to enable the tfp0

**Comment by timonline** [comment]
I tried using 0xffffff8004536000 in the config file and the cl0ver slide works but crashes on cl0ver dump

**Comment by Siguza** [comment]
For your iPhone6,1/9.3.3 there are firmware keys available, see [here](https://www.theiphonewiki.com/wiki/Genoa_13G34_(iPhone6,1)).  
Just extract/decrypt the kernel from the IPSW, put it at `/etc/cl0ver/kernel.bin` and you're all set.

**Comment by timonline** [comment]
you could not have a better timing.

Been trying to decrypt it for the last 4 hours

Used this command:

 ./xpwntool kernelcache.release.n51 kernelcache.decrypted -iv 06ae5b6dce2bc7c7299d0f55b066d680 -key 13c4bd389af426285e68d22c396e208f51c5d02b3dd5d3d42e01a3ce905d2c4b -decrypt

The above IV and key were from the wiki, now the command doesn't fail but it doesn't look like it decrypted it

$ diff kernelcache.release.n51 kernelcache.decrypted

the above product no output meaning they are identical

**Comment by Siguza** [comment]
xpwntool doesn't support IMG4 files, try xerub's [img4tool](https://github.com/xerub/img4tool) instead. Worked for me with:

    img4tool -image kernelcache.release.n51 kernel.bin 06ae5b6dce2bc7c7299d0f55b066d68013c4bd389af426285e68d22c396e208f51c5d02b3dd5d3d42e01a3ce905d2c4b

**Comment by timonline** [comment]
yeah i figure img4 but wasn't 100%

Not sure if the following is a significant error

./img4 -image kernelcache.release.n51 kernel.bin 06ae5b6dce2bc7c7299d0f55b066d68013c4bd389af426285e68d22c396e208f51c5d02b3dd5d3d42e01a3ce905d2c4b
krnl
[i] extra 0x9002 bytes after compressed chunk

Some outputs:

$ ls kernel.bin 
kernel.bin

$ cksum kernel.bin 
3065428140 27017216 kernel.bin

Once you confirm this extra byte output is not a problem, i can give it a shot

**Comment by Siguza** [comment]
That's perfectly fine, it's just KPP being skipped there.

**Comment by timonline** [comment]
ok, giving it a shot.

I apologize, kind of a newbie in kernel decrypting

**Comment by timonline** [comment]
Yep, that worked.

I got the "[*] Successfully installed patch" message

By the way you can add  0xffffff8004536000 under iPhone 6,1 9.3.3

Think we can also create an offset.dat for that combination?

**Comment by Siguza** [comment]
If you ran it as root, it should've already created an offsets file at `/etc/cl0ver/`... I guess adding that to the registry saves people the time to decrypt kernels, so... you're welcome to upload it. :)

**Comment by timonline** [comment]
sure I can add the offsets in offset.c and offset.dat then request merge

**Comment by timonline** [comment]
please close this and thanks

**Comment by Siguza** [comment]
You're welcome. :)

**Comment by 0neday** [comment]
@Siguza Thank your help
