### ISSUE TITLE
Unsupported device: iPad mini 4 (J97AP) / iOS 9.0.2 (13A452)

### ISSUE THREAD

**Issue by johnsoninnyc** [Siguza/cl0ver#44]
late-in-the-signing-window request here  -  so i have a mini4 / cellular on JB 9.0.2 and turns out I seem to have valid blobs for 10.2.    Will the ipad air2 offsets work on this?   If no how can I assist in getting support for this device before 10.3 releases / 10.2.1 closes?   many thanks!

**Comment by Siguza** [comment]
The iPad Air 2 looks like a bad candidate, but at least on 10.2.1, the iPad mini 4 has offsets identical to those of the iPhone 6. So maybe give [these offsets](https://raw.githubusercontent.com/Siguza/cl0ver/master/offsets/N61AP_13A452/offsets.dat) a try? :)

**Comment by Siguza** [comment]
Times have changed and we have decryption keys now. :)

Download [this zip](https://github.com/Siguza/cl0ver/files/2397922/Archive.zip), extract it and move the files to /etc/cl0ver/ on your device, then run `./cl0ver` without any arguments.

**Comment by gummykage** [comment]
Thank you Siguza I'll try them today and report back!

**Comment by gummykage** [comment]
Siguza, my ipad mini 4 just reboots with a kernel panic everytime. It's an ipad Mini 4 128gb Cellular version. Is this normal?

**Comment by gummykage** [comment]
It kernel panics on Executing ROP chain

**Comment by gummykage** [comment]
WAIT My mistake it works. Successfully. i had an offset file with the kernel.bin and the config.txt from testing other ones before. Attempting to set nonce now. Thank you so much!!!!!

**Comment by Siguza** [comment]
Alright, I'll close this one too as resolved then. :)
