### ISSUE TITLE
Unsupported device: iPhone 6s (N71AP) / iOS 9.0 (13A342)

### ISSUE THREAD

**Issue by marceloueda** [Siguza/cl0ver#45]
I've run ./cl0ver panic several times (10+) and I got no panic log. Could I try anything different?

**Comment by marceloueda** [comment]
Nevermind, just tried with the config.txt and offsets.dat provided in #41 and worked fine! Thanks!

**Comment by Siguza** [comment]
Oh, cool. Adding them to the list then. :)
