### ISSUE TITLE
Unsupported device/OS combination iPod 6 (n102ap) IOS 9.0.2

### ISSUE THREAD

**Issue by jlozes** [Siguza/cl0ver#47]
This device is not yet compatible with cl0ver. Even when I try "cl0ver dump", the message "Unsupported device/OS combination" is displaied and "kernel.bin" file is not created.

I join the kernel panic and the log file of the command "cl0ver panic log=log.txt". I hope this can help you, and me at the same time.

[logs.zip](https://github.com/Siguza/cl0ver/files/1049416/logs.zip)

**Comment by Siguza** [comment]
The iPod touch 6G should have the same offsets as the iPhone 6. Could you try this please:

1. Put this in `/etc/cl0ver/config.txt`:

       0xffffff800454a000
       0xffffff8004503168

2. Download [this file](https://raw.githubusercontent.com/Siguza/cl0ver/master/offsets/N61AP_13A452/offsets.dat) and save it at `/etc/cl0ver/offsets.dat`.

Then run `./cl0ver`.

**Comment by jlozes** [comment]
Doesn't work, kernel panic. I join the log files for the command "./cl0ver" (noted "patch" and for the command "./cl0ver dump" (noted "kernel_dump").

The logs files are extracted from my ssh terminal because the param "log=xxx" gave me an empty file.

I've tried with and without airplane mode on. Is it realy important to have airplane mode on when patching?

If you know how to find the kernel panic logs files via sftp, this could help me so mutch.

To explain quickly why I ask you this two questions, this is because I'm blind and "mterminal" is not accessible with VoiceOver (I can enter commands but I can't read output) and it's a little dificult to select all the kernel panic log text in the setings screen.

For information, I've also try to patch with and without VoiceOver active.

Thank for your help.

[logs2.zip](https://github.com/Siguza/cl0ver/files/1049740/logs2.zip)

**Comment by Siguza** [comment]
Panic logs are saved under `/var/mobile/Library/Logs/CrashReporter/panic-*.ips`.  
And airplane mode should only matter when dumping the kernel not for anything else (and even then it has a limited impact).

But alright, never got a panic log like that one before. I'll have a thorough look at it tonight and see what I can figure out.

**Comment by jlozes** [comment]
Thanks for the informations, I didn't think to look on this path. More easy for me now to export my logs.

I'll wait for your advice on my strange panic but I prepare my device for a factory reset, maybe an incompatibility with something wich is or has been installed, even if I haven't installed lots of twiks and apps.

Thanks again.

**Comment by Siguza** [comment]
No no no, factory reset will render your device unable to boot (at least the reset from the Settings app). Also, there's practically no third-party software that even touches the code cl0ver interacts with, so you should be safe from incompatibilities.

Two offsets from the offsets.dat simply don't match up. Could you try dumping a few more times?

**Comment by jlozes** [comment]
For the reset, it was the one of the setings app that I was talking about.

I have tried lots of kernel dump before because when I have read your readme, I have seen the fact that kernel dump was very instable and I've done it probably more than 20 but with no luck. 

But I succesfuly dump my kernel.bin via ssh, after lots of kernel panics but it has worked finaly, and the command "./cl0ver" succesfuly patch the kernel, after only one kernel panic. I test it with "NonceEnabler" and the patch work also, everything is OK. I have realy apreciated your helps, thanks a lot and sory th have wasted your time because I haven't insisted enough on kernel dumping.

I attach also my offsets.dat file and if you need an other file like my kernel.bin, I will edit this message to add it but I think you don't need it.


[offsets.dat.zip](https://github.com/Siguza/cl0ver/files/1051141/offsets.dat.zip)

**Comment by Siguza** [comment]
Hey, no need to be sorry. I'm happy to help, and you expanded the offsets collection, so thank you for that. :)
