### ISSUE TITLE
Unsupported device/OS combination iPhone 6 (N61AP) iOS 9.0.1 (13A404)

### ISSUE THREAD

**Issue by meowgang** [Siguza/cl0ver#49]
Hello There!

Firstly, thanks for such an awesome tool. This worked on my 6+ great but I ran into some issues on my gf's 6. Any guidance you can provide would be so helpful! Thanks!

Offsets from: https://raw.githubusercontent.com/Siguza/cl0ver/master/offsets/N61AP_13A405/offsets.dat

Unhandled error: Unsupported device/iOS Combination on ./cl0ver slide

Added config file with:
0xffffff800454a000
0xffffff8004503168

The config file allowed me to get past ./cl0ver slide but the phone crashed on ./cl0ver
The phone also crashed on ./cl0ver dump

I removed the config file and generated the panic file here: https://pastebin.com/WZEvACCK

**Comment by meowgang** [comment]
Nevermind, I solved it by deleting the offsets file and dumping the bin. I've attached the created offsets file here.
[offsets.zip](https://github.com/Siguza/cl0ver/files/1137552/offsets.zip)

**Comment by mwelleco** [comment]
I'm sorry, but I don't know what I have to do now... :/
