### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by aleondopeso** [Siguza/cl0ver#5]
When i write Make on Mac OS with Xcode, they said. Can someone solve?
<img width="1280" alt="captura de pantalla 2016-12-29 a las 17 23 30" src="https://cloud.githubusercontent.com/assets/21337100/21548259/99b9e674-cdeb-11e6-818d-16b2a451772a.png">

**Comment by Siguza** [comment]
It seems weird that this would be the first command executed by the makefile... if you had initial trouble, maybe the include directory got messed up. In that case, try `make clean && make`.
Otherwise, does the `include` directory contain a symlink named `IOKit` that points to `/System/Library/Frameworks/IOKit.frameworkHeaders`?

**Comment by Siguza** [comment]
Ugh, that doesn't sound good. Are you on Sierra?

Does this directory exist?:

    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework//Headers

**Comment by aleondopeso** [comment]
Yes, i'm on sierra and that directory exists

**Comment by Siguza** [comment]
I just pushed some changes that will hopefully fix your problems. Could you pull and try again?

**Comment by aleondopeso** [comment]
Okey, it works now. and what´s the next step to jailbreak my phone? 
<img width="1280" alt="captura de pantalla 2016-12-30 a las 23 01 51" src="https://cloud.githubusercontent.com/assets/21337100/21573383/155e89b2-cee4-11e6-92dd-8e626705afac.png">

**Comment by Siguza** [comment]
This isn't a jailbreak.  
This is meant to be used alongside a jailbreak, to add a missing kernel patch. It *could* be turned into a jailbreak with a lot of effort, but I see no reason for that, as Pangu's jailbreaks cover basically the same iOS versions as this.  
My tool is also far from complete, and if you want to use it on a jailbroken device, you're first gonna have to run `./cl0ver panic` and send me cl0ver's output as well as the panic log, so I can add basic support for that device and iOS combination.
