### ISSUE TITLE
Unsupported device: iPad mini 3 (J85mAP) / iOS 9.0.2 (13A452)

### ISSUE THREAD

**Issue by ngoctnq** [Siguza/cl0ver#50]
I've tried with the iPad Mini 2 offsets but it doesn't work.

Here's the `panic.ips` (changed to txt for upload purposes): [panic-2017-09-16-172919.txt](https://github.com/Siguza/cl0ver/files/1308687/panic-2017-09-16-172919.txt)
Here's the panic log: [log.txt](https://github.com/Siguza/cl0ver/files/1308688/log.txt)

~~Here is my attempted `config.txt`: [config.txt](https://github.com/Siguza/cl0ver/files/1308689/config.txt). Please tell me if I extracted the numbers correctly.~~
~~Here's the log when I ran `./clover`: [log0.txt](https://github.com/Siguza/cl0ver/files/1308692/log0.txt)~~
~~Same "kernel slide not multiple of 0x100000" error when I try dumping.~~

After reading a few issues closed that's definitely the wrong numbers. Could you give the me the correct one, and explain how if that isn't too long.

Please advice what I need to do next.

**Comment by Siguza** [comment]
Things have changed a little since last winter, [keys are available for your device/version now](https://www.theiphonewiki.com/wiki/Monarch_13A452_(iPad4,7)).

Create this as `/etc/cl0ver/config.txt`:

    0xffffff800453e000
    0

Then use the keys to extract/decrypt your kernelcache (if you have no tool already, use [img4tool](https://github.com/xerub/img4tool)) and place the result at `/etc/cl0ver/kernel.bin`.

**Comment by ngoctnq** [comment]
Sorry if this is a little too much of a newbie question, but I cannot compile xerub's img4tool due to not knowing how to `ln` openssl stuffs. I then happen to come up to a precompiled binary on a "reverse engineer iOS 10" reddit post, and try that with
```./img4tool -image iPad4,7_9.0.2_13A452_Restore/Firmware/all_flash/all_flash.j85map.production/sep-firmware.j85m.RELEASE.im4p kernel.bin 9ec79288ac062987edfadfe36a18bc43570dc346bd1c808f1c8b82aa3ee98f9cca7b845e1b9342a07ddbe46d56db085d```
The output is only "sepi".
Did I do it right? For the parameter [ivkey], do I append those two or just the IV/Key?

Also when I try to run cl0ver again with **only** the new config.txt, it just gives me "Unsupported device/OS combination" again.

**Comment by Siguza** [comment]
Eh, you extracted SEP instead of the kernel. Key looks correct, but try with `-image iPad4,7_9.0.2_13A452_Restore/kernelcache.release.j85m` instead.

**Comment by ngoctnq** [comment]
You're the man! That worked wonders.
