### ISSUE TITLE
iPhone 6s+ - iOS 9.1 Support

### ISSUE THREAD

**Issue by Demavex** [Siguza/cl0ver#52]
I haven't actually tried it yet but I see that iPhone 6s+ on 9.1 isn't supported/has no offsets added. Any way to get these offsets?

**Comment by Siguza** [comment]
9.1 should have tfp0 enabled by default anyway. So yeah, you could use `kdump` to dump the kernel and put the file in `/etc/cl0ver/kernel.bin`, but there's no real point since there's nothing cl0ver can do for you on that version...

**Comment by Siguza** [comment]
I presume you resolved your issue somehow? I'm closing this as "declined" for now, please comment if you feel this isn't right.
