### ISSUE TITLE
Unsupported device: iPad mini 3 (J85mAP) / iOS 9.0.2 (13A452)

### ISSUE THREAD

**Issue by forloop8** [Siguza/cl0ver#54]
As you requested, following are the log files:

output: https://pastebin.com/yY5Le9Xd
cl0ver panic logfile: https://pastebin.com/udeSC87H

Let me know if you need further information.

Thanks.

**Comment by Siguza** [comment]
[Firmware keys are available for you](https://www.theiphonewiki.com/wiki/Monarch_13A452_(iPad4,7)). Just decrypt your kernel, place it at `/etc/cl0ver/kernel.bin` and everything should work out.

**Comment by forloop8** [comment]
Thanks for your response,   what values I need to put in config file?

cl0ver slide:    https://pastebin.com/3iNChb1K
cl0ver panic:     https://pastebin.com/zwE3Dyyj
panic.ips :      https://pastebin.com/DbXYXtir

Thanks,

**Comment by Siguza** [comment]
Should be this:

    0xffffff800453e000
    0x0

**Comment by forloop8** [comment]
Successful patch the kernel. 
Thanks for your help and support.

**Comment by forloop8** [comment]
Just attached my offsets.dat file in case someone needs it.

[offsets.zip](https://github.com/Siguza/cl0ver/files/1777038/offsets.zip)
