### ISSUE TITLE
Unsupported device: iPad Air 2 (J82AP) / iOS 9.0.2

### ISSUE THREAD

**Issue by sstocker85** [Siguza/cl0ver#55]
Hello, 
I also try to patch my iPad Air 2 and I get the unsupported device message.

Here are my logs:
IPS: https://pastebin.com/AHSNQVTL
Panic Log: https://pastebin.com/aRRta

Thanks.

**Comment by Siguza** [comment]
Firmware Keys: https://www.theiphonewiki.com/wiki/Monarch_13A452_(iPad5,4)  
Decrypt your kernel & place it in `/etc/cl0ver/kernel.bin`.

**Comment by sstocker85** [comment]
thanks for your quick answer.
I already made this step and extracted the kernel.bin, but I do not know which values I should write in my config.txt

**Comment by Siguza** [comment]
Get me the output of `./cl0ver slide` and the _subsequent_ panic log from a `./cl0ver panic`.

**Comment by sstocker85** [comment]
here are my files:
cl0ver slide: https://pastebin.com/81LAeptY
cl0ver panic: https://pastebin.com/UMrsGhfR
panic.ips: https://pastebin.com/y3Fdzp6Q

**Comment by Siguza** [comment]
Alright, set up config.txt like this:

    0xffffff800454a000
    0x0

**Comment by sstocker85** [comment]
still getting: Unhandled error: Unsupported device/OS combination [src/lib/offsets.c:85 reg_anchor] when I run ./cl0ver
are you sure with the second line ?

**Comment by Siguza** [comment]
Uh yeah, pretty sure... can you post the full console output?

**Comment by sstocker85** [comment]
here it is:
https://pastebin.com/XtHSWBXA

**Comment by Siguza** [comment]
It doesn't find the config file... is it called `/etc/cl0ver/config.txt` exactly?

**Comment by sstocker85** [comment]
You are right, there was a typo -sorry for that.
But now I get a new error:
No offsets loaded so far, checking for dumped kernel... [src/lib/offsets.c:308 off_init]
Segmentation fault: 11
Here is the full output: https://pastebin.com/dCS9DBbH
I guess, it's something wrong with the kernel.bin?

**Comment by sstocker85** [comment]
[*] Successfully installed patch :)
Forgot the IV when I extracted the kernel.bin with img4tools
A big thank you for your support.

**Comment by Siguza** [comment]
Sure, np. :)
