### ISSUE TITLE
Unsupported device/OS combination - J82AP iOS   9.0.1 Ipad Air2

### ISSUE THREAD

**Issue by ashdriver** [Siguza/cl0ver#57]
Hi Siguza - not sure if you are still active with this tool, but here are panic dumps for the above device/ ios combo. If you get the time, a config be very useful to me! Thanks!
[panic_output.txt](https://github.com/Siguza/cl0ver/files/1848338/panic_output.txt)

[panic-2018-03-26-161128.zip](https://github.com/Siguza/cl0ver/files/1848361/panic-2018-03-26-161128.zip)

**Comment by Siguza** [comment]
Config:

```
0xffffff800454a000
0x0
```

Kernel you can decrypt, keys here: https://www.theiphonewiki.com/wiki/Monarch_13A404_(iPad5,4)

**Comment by ashdriver** [comment]
Looks good - very much appreciated! Thank you.
