### ISSUE TITLE
Unsupported device/OS combination iPad Air 2 (J81AP) iOS 9.0. (13A344) 

### ISSUE THREAD

**Issue by MrVibez** [Siguza/cl0ver#58]
Hey I do not understand that much here
How i entcrypt the kernelcache?

Panic log:
https://pastebin.com/v4gtb0h6
Output:
https://pastebin.com/EYRy47Ub

**Comment by Siguza** [comment]
Put this at `/etc/cl0ver/config.txt`:

    0xffffff801694a000
    0x0

Then [decrypt your kernel](https://www.theiphonewiki.com/wiki/Monarch_13A344_(iPad5,3)), put it at `/etc/cl0ver/kernel.bin` and you should be good to go.

**Comment by MrVibez** [comment]
Thank you! How do I decrypt the kernel, need to use the kernelcache key?
