### ISSUE TITLE
Cl0ver crashes iPad Air 9.0.2 Supported Device

### ISSUE THREAD

**Issue by BartuHTC** [Siguza/cl0ver#61]
Even though the iPad is jailbroken with Pangu, whenever `./clvoer` is executed the device crashes and subsequently reboots. 

`./cl0ver slide` output:  [https://paste.ee/p/Bc0HF](url)
`./cl0ver panic` output:  [https://paste.ee/p/lIzkk](url)
ips file contents with pc=0xffffff8004e7df00: [https://paste.ee/p/BpU7U](url)
ips file: [https://drive.google.com/open?id=0B0HxnpSimeNlY3FBbkdGd1lFZWtGeTVPbTlSUzl5TXJaRHNz](url)

**Comment by Siguza** [comment]
What is the panic log from just running `./cl0ver` though, without any arguments?

**Comment by BartuHTC** [comment]
What do you mean? It goes something like this:
'iPad:/private/var/root root# ./cl0ver panic
[*] Checking for config file... [src/lib/offsets.c:176 off_cfg]
[*] Yes, attempting to read anchor and vtab from config file... [src/lib/offsets.c:187 off_cfg]
[*] Anchor: 0xffffff800453e000, Vtab (unslid): 0xffffff80044f7168 [src/lib/offsets.c:191 off_cfg]
[*] Using info leak to get kernel slide... [src/lib/slide.c:64 get_kernel_slide]'

**Comment by Siguza** [comment]
I said **without any arguments**. Just `./cl0ver`. No `slide` or `panic`.

**Comment by BartuHTC** [comment]
Sorry, here you go: [https://paste.ee/p/9bPVx](url)

**Comment by Siguza** [comment]
Download [this file](https://raw.githubusercontent.com/Siguza/cl0ver/master/offsets/J72AP_13A452/offsets.dat) and put it in `/etc/cl0ver/offsets.dat`, then run `./cl0ver` again.

**Comment by BartuHTC** [comment]
Thank you very much, this fixed the problem completely.
