### ISSUE TITLE
Unsupported Device: iPad Air 2 (J81AP) iOS 9.0.1 (13A404)

### ISSUE THREAD

**Issue by mkahly** [Siguza/cl0ver#64]
iPad Air 2 (iPad5,3) running iOS 9.0.1.  Trying to get tfp0.  Thank you in advance for your assistance.

[cl0ver panic log.txt](https://github.com/Siguza/cl0ver/files/2195421/cl0ver.panic.log.txt)
[cl0ver log.txt](https://github.com/Siguza/cl0ver/files/2195423/cl0ver.log.txt)
[cl0ver slide log.txt](https://github.com/Siguza/cl0ver/files/2195424/cl0ver.slide.log.txt)
[panic diagnostics report.txt](https://github.com/Siguza/cl0ver/files/2195454/panic.diagnostics.report.txt)
[panic.txt](https://github.com/Siguza/cl0ver/files/2195461/panic.txt)

**Comment by Siguza** [comment]
This config should work for you (`/etc/cl0ver/config.txt`):

    0xffffff800454a000
    0x0

And with [these keys](https://www.theiphonewiki.com/wiki/Monarch_13A404_(iPad5,3)) you should be able to decrypt your kernel (and put at `/etc/cl0ver/kernel.bin`).

**Comment by mkahly** [comment]
Thank you for your assistance.  How do I use the keys to decrypt the kernel?

**Comment by Siguza** [comment]
With [img4lib](https://github.com/xerub/img4lib/).

    img4 -i kernelcache -o kernel -k IVKEY
