### ISSUE TITLE
iPhone6(N61AP)/IOS9.3(13E233) Unsupported device/OS combination

### ISSUE THREAD

**Issue by lincolnfz** [Siguza/cl0ver#65]
Unhandled error: Unsupported device/OS combination

i had update lastet version.

**Comment by Siguza** [comment]
For 9.3.x, [jbme.qwertyoruiop.com](https://jbme.qwertyoruiop.com) has tfp0.

**Comment by lincolnfz** [comment]
in my device often cause panic. emm, how can i solve it. could u give me some brief hint?

 "build" : "iPhone OS 9.3.2 (13F69)",
  "product" : "iPhone7,2",
  "kernel" : "Darwin Kernel Version 15.5.0: Mon Apr 18 16:44:06 PDT 2016; root:xnu-3248.50.21~4\/RELEASE_ARM64_T7000",
  "incident" : "C762DA16-9BA0-4DD6-B560-4772B0DEF8F8",
  "crashReporterKey" : "12b9a2816c4c7a381cbe6b786059328159c32edf",
  "date" : "2018-07-27 16:31:56.56 +0800",
  "panicString" : "Debugger message: WDT timeout\n10s ago: 3000b50 3000f0 3000r6e58f000 3000m0\/1 2800m10004003\/1 2800l1 2800nffffffff 2600m10004003\/1 2600l1 2600u0 2400m10004003\/1 2400l1 2400u0 2400bff 2200m10004003\/1 2200l1 2200u0 2000m10004003\/1 2000l1 2000u0 1800m10004003\/1 1800c105 1800l1 1800u0 1797d105 1600m10004003\/1 1600l1 1600u0 1400m10004003\/1 1400l1 1400u0 1200m10004003\/1 1200l1 1200u0 1000m10004003\/1 1000l1 1000u0 800m10004003\/1 800l1 800u0 600m10004003\/1 600c310 600g2 600l1 600u0 597d310 400m10004003\/1 400g2 400l1 400u0 200m10004003\/1 200g2 200l1 200u0 0m10004003\/1 0g2 0l1 0u0 \nOS version: 13F69\nKernel version: Darwin Kernel Version 15.5.0: Mon Apr 18 16:44:06 PDT 2016; root:xnu-3248.50.21~4\/RELEASE_ARM64_T7000\niBoot version: iBoot-2817.50.3\nsecure boot?: YES\nPaniclog version: 5\nKernel slide:     0x000000001fe00000\nKernel text base: 0xffffff8023e04000\nEpoch Time:        sec       usec\n  Boot    : 0x5b5ad6e2 0x00000000\n  Sleep   : 0x00000000 0x00000000\n  Wake    : 0x00000000 0x00000000\n  Calendar: 0x5b5ad85d 0x000ab612\n\nTotal cpu_usage: 25327764\nThread task pri cpu_usage\n0xffffff8000841800 kernel_task 0 4717972\n0xffffff80009e6800 kernel_task 0 7623205\n\nPanicked task 0xffffff8000833580: 30394 pages, 188 threads: pid 0: kernel_task\npanicked thread: 0xffffff8000841800, backtrace: 0xffffff8024318a20\n\t\t  lr: 0xffffff8023f02608  fp: 0xffffff8024318a70\n\t\t  lr: 0xffffff8024485ca4  fp: 0xffffff8024318f40\n\t\t  lr: 0xffffff802551f08c  fp: 0xffffff8024318fd0\n\t\t  lr: 0xffffff802424d9a4  fp: 0xffffff8024318fe0\n\t\t  lr: 0xffffff8023ef926c  fp: 0xffffff8024318ff0\n\t\t  lr: 0xffffff8023e3c44c  fp: 0xffffff81693fbca0\n\t\t  lr: 0xffffff8023eff380  fp: 0x0000000000000000\n\n    \n",
  "memoryStatus" : {"compressorSize":181,"compressions":41409,"decompressions":4986,"busyBufferCount":0,"jetsamLevel":0,"pageSize":4096,"memoryPressure":{"pagesWanted":0,"pagesReclaimed":0},"memoryPages":{"active":125988,"throttled":0,"fileBacked":112141,"wired":41877,"purgeable":15,"inactive":16125,"free":45098,"speculative":23209}},
