### ISSUE TITLE
iPad mini 2 (J86AP) + iOS 9.0.2 (13A452)

### ISSUE THREAD

**Issue by cdpwind** [Siguza/cl0ver#68]
Please check this panic log.
[panic.log](https://github.com/Siguza/cl0ver/files/2390775/panic.log)

**Comment by Siguza** [comment]
Download [this zip](https://github.com/Siguza/cl0ver/files/2397889/Archive.zip), extract it and move the files to `/etc/cl0ver/` on your device.  
Then run `./cl0ver`.

**Comment by cdpwind** [comment]
Thank you for an attached file.
I've tried to patch my iPad with an attached file and it works greatly.
I've got a message "Successfully installed patch".

**Comment by Siguza** [comment]
Alright, I'll close this as resolved then. :)
