### ISSUE TITLE
iPad Mini 4 9.0.2 Unsupported Configuration

### ISSUE THREAD

**Issue by gummykage** [Siguza/cl0ver#69]
Hi Siguza thank you for your time on this.

Panic log and ssh output. Is there some way to get the tfp0? Trying to upgrade to 11.3.1 with valid shsh blobs with futurerestore.

[ipadmini4sshoutput.txt](https://github.com/Siguza/cl0ver/files/2393496/ipadmini4sshoutput.txt)
[panic-2018-09-18-084604.ips.txt](https://github.com/Siguza/cl0ver/files/2393504/panic-2018-09-18-084604.ips.txt)

**Comment by Siguza** [comment]
Closing this as duplicate of #44.
