### ISSUE TITLE
unsupported device N102AP ipod6 9.0.1

### ISSUE THREAD

**Issue by snam11** [Siguza/cl0ver#73]
as the title says, i get error on my device:
[*] Model: N102AP [src/lib/device.c:34 get_model_internal]
[!] Unhandled error: Unsupported device/OS combination [src/lib/offsets.c:85 reg_anchor]

of course is also impossible to set nonce using terminal, 
nvram: Error setting variable - 'com.apple.System.boot-nonce': (iokit/common) general error

i've attached a panic log i've created using ./cl0ver panic
[panic-2019-07-22-230010.ips.zip](https://github.com/Siguza/cl0ver/files/3419196/panic-2019-07-22-230010.ips.zip)

there is a chance to run cl0ver with modded asset.dat from terminal or shsh?

**Comment by Siguza** [comment]
Download [this file](https://github.com/Siguza/cl0ver/files/3419640/kernel.bin.zip), extract it, put the result at `/etc/cl0ver/kernel.bin` on your device, then run `./cl0ver` again with no args.

**Comment by snam11** [comment]
i've put in /etc/cl0ver both, set permissions to 777 and run: 

[*] Checking for config file... [src/lib/offsets.c:176 off_cfg]
[*] Nope, let's hope the registry has a compatible anchor & vtab... [src/lib/offsets.c:181 off_cfg]
[*] OS build: 13A404 [src/lib/device.c:102 get_os_version_internal]
[*] Page size: 0x0000000000001000 [src/lib/uaf_rop.c:113 uaf_rop_stack]
[*] Allocating ROP stack page at 0x000000000c000000 [src/lib/uaf_rop.c:117 uaf_rop_stack]
[*] Allocated ROP page at 0x000000000c000000 [src/lib/uaf_rop.c:123 uaf_rop_stack]
[*] Initializing offsets... [src/lib/offsets.c:253 off_init]
[*] Checking for offsets cache file... [src/lib/offsets.c:266 off_init]
[*] Using info leak to get kernel slide... [src/lib/slide.c:64 get_kernel_slide]
[*] Dict: [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[0]: 0x000000d3 [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[1]: 0x81000002 [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[2]: 0x08000004 [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[3]: 0x006c6f6c [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[4]: 0x84000400 [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[5]: 0x69696969 [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[6]: 0x69696969 [src/lib/slide.c:33 get_kernel_anchor]
[*] Spawning user client / Parsing dictionary... [src/lib/io.c:59 _io_spawn_client]
[*] Getting IO service handle... [src/lib/io.c:45 _io_get_service]
[*] Getting IO master port... [src/lib/io.c:30 get_io_master_port]
[*] Creating dict iterator... [src/lib/io.c:72 _io_iterator]
[*] Getting next element from iterator... [src/lib/io.c:84 _io_next]
[*] Releasing user client... [src/lib/io.c:131 _io_release_client]
[*] Kernel stack: [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 0]: 0x6969696969696969 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 1]: 0xffffff802234a000 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 2]: 0x00000000ff002bf1 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 3]: 0xffffff8000d895cc [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 4]: 0xffffff80036180b4 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 5]: 0xffffff8003602300 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 6]: 0xffffff8000d895a0 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 7]: 0xffffff801fc6b950 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 8]: 0xffffff8021ed4edc [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 9]: 0x0000000000000000 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[10]: 0xffffff8022350a50 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[11]: 0xffffff8000d89000 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[12]: 0xffffff802239ecc8 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[13]: 0x0000000000001074 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[14]: 0x0000000000000000 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[15]: 0xffffff802239e050 [src/lib/slide.c:44 get_kernel_anchor]
[*] Getting anchor address from registry... [src/lib/offsets.c:37 reg_anchor]
[*] Model: N102AP [src/lib/device.c:34 get_model_internal]
[!] Unhandled error: Unsupported device/OS combination [src/lib/offsets.c:85 reg_anchor]

**Comment by Cryptiiiic** [comment]
iPod 6 9.0.1 (iPod7,1 N102AP 13A404) offsets for reg_anchor and reg_vtab are the same as iPod 6 9.0.2 (iPod7,1 N102AP 13A452).
Here is the diff:

`
diff --git a/src/lib/offsets.c b/src/lib/offsets.c
index 8827927..f15a085 100644
--- a/src/lib/offsets.c
+++ b/src/lib/offsets.c
@@ -42,8 +42,6 @@ static addr_t reg_anchor(void)
         case M_J97AP  | V_13A404:
         case M_N56AP  | V_13A452:
         case M_N61AP  | V_13A404:
-        case M_N102AP | V_13A404:
-            return 0xffffff800454a000;
         case M_N61AP  | V_13A452:
         case M_N102AP | V_13A452:
             return 0xffffff800454a000;
@@ -98,8 +96,6 @@ static addr_t reg_vtab(void)
         case M_J97AP  | V_13A404:
         case M_N56AP  | V_13A452:
         case M_N61AP  | V_13A404:
-        case M_N102AP | V_13A404:
-            return 0xffffff8004503168;
         case M_N61AP  | V_13A452:
         case M_N102AP | V_13A452:
             return 0xffffff8004503168;`

**Comment by snam11** [comment]
@iCryptiiiic 'm not an expert, what does it mean? i have to use different offsets?
i dunno how to compile it, can you help me out?
thanx

**Comment by Cryptiiiic** [comment]
![image](https://user-images.githubusercontent.com/27748705/61703888-6a30e680-acf7-11e9-9260-076be2b8717b.png)
This can be closed if my diff is implemented. I don't feel like making a pull for 4 lines of code.
