### ISSUE TITLE
iPad 4 (iPad3,6) on iOS 9.0.2 (jailbroken)

### ISSUE THREAD

**Issue by hieplpvip** [Siguza/cl0ver#9]
I jailbroke my iPad with Pangu. Do you know if tfp0 is patched?

**Comment by Siguza** [comment]
I'm pretty sure it is not. But you can test that with [kern-utils](https://github.com/Siguza/ios-kern-utils/releases). Just run e.g. `kmap` as root and see whether it fails at getting the kernel task.

**Comment by Siguza** [comment]
It seems no further action from me is required; I'm closing this issue.
